/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JaRouteImport } from './routes/ja'
import { Route as KoRouteImport } from './routes/ko'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ZhHantRouteImport } from './routes/zh-Hant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantRoute = ZhHantRouteImport.update({
  id: '/zh-Hant',
  path: '/zh-Hant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh-Hant': typeof ZhHantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh-Hant': typeof ZhHantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh-Hant': typeof ZhHantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ja' | '/ko' | '/sitemap.xml' | '/zh-Hant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ja' | '/ko' | '/sitemap.xml' | '/zh-Hant'
  id: '__root__' | '/' | '/ja' | '/ko' | '/sitemap.xml' | '/zh-Hant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JaRoute: typeof JaRoute
  KoRoute: typeof KoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZhHantRoute: typeof ZhHantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-Hant': {
      id: '/zh-Hant'
      path: '/zh-Hant'
      fullPath: '/zh-Hant'
      preLoaderRoute: typeof ZhHantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JaRoute: JaRoute,
  KoRoute: KoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZhHantRoute: ZhHantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
